apiVersion: v1
kind: ConfigMap
metadata:
  name: faraja-config
  namespace: faraja-ns
  labels:
    team: cne01
    environment: development
    project: faraja
    app: faraja
data:
  APP_ENV: development
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: faraja
  DB_USER: postgres
  API_PORT: "8000"
  NEXT_PUBLIC_API_BASE_URL: http://backend:8000
