apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: faraja-ns
  labels:
    app: frontend
    tier: frontend
    team: cne01
    project: faraja
spec:
  type: ClusterIP
  selector:
    app: frontend
    tier: frontend
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http