apiVersion: v1
kind: Secret
metadata:
  name: faraja-db-secret
  namespace: faraja-ns
  labels:
    team: cne01
    environment: development
    project: faraja
    app: faraja-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
