apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: faraja-ns
  labels:
    team: cne01
    environment: development
    project: faraja
    app: faraja-db
spec:
  type: ClusterIP
  selector:
    app: faraja-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP

